import { motion } from "framer-motion";
import { Link } from "react-router-dom";

const features = [
  ["AI", "AI Job Matching", "Discover roles that align with your skills and profile."],
  ["CV", "Resume Analysis", "Understand resume strengths and surface relevant skills."],
  ["AP", "Job Applications", "Apply, track progress, and keep opportunities in one place."],
  ["RD", "Recruiter Dashboard", "Create roles, review applicants, and manage hiring."],
  ["NT", "Notifications", "Stay informed about applications and hiring decisions."],
  ["IQ", "AI Interview", "Practice responses and receive structured feedback."],
];

const workflows = [
  ["For candidates", "Move from profile to opportunity with AI-assisted guidance.", ["Build your profile", "Get AI matches", "Apply with confidence"], "from-purple-600/30 to-indigo-600/10"],
  ["For recruiters", "Move from job post to shortlist with a focused hiring workflow.", ["Post an opportunity", "Review applicants", "Find the right fit"], "from-fuchsia-600/25 to-purple-600/10"],
];

function Home() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-[#08070d] text-white">
      <div className="pointer-events-none absolute -left-40 top-0 h-[34rem] w-[34rem] rounded-full bg-purple-700/20 blur-[130px]" />
      <div className="pointer-events-none absolute right-0 top-[30rem] h-[30rem] w-[30rem] rounded-full bg-fuchsia-700/15 blur-[130px]" />
      <main className="relative z-10">
        <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-20 md:px-10 lg:grid-cols-[1.02fr_.98fr] lg:px-12 lg:pt-28">
          <motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <div className="inline-flex items-center gap-2 rounded-full border border-purple-400/30 bg-purple-500/10 px-4 py-2 text-sm font-medium text-purple-200"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_14px_#34d399]" />SmartHire-AI · intelligent recruitment</div>
            <h1 className="mt-7 max-w-3xl text-5xl font-bold leading-[1.04] tracking-tight md:text-6xl lg:text-7xl">Hire smarter.<span className="block bg-gradient-to-r from-purple-300 via-fuchsia-300 to-pink-300 bg-clip-text text-transparent">Find work that fits.</span></h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-400">SmartHire-AI brings candidates, recruiters, resumes, and opportunities together in one focused AI-powered recruitment platform.</p>
            <div className="mt-9 flex flex-wrap gap-4"><Link to="/signup"><motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.98 }} className="rounded-xl bg-gradient-to-r from-purple-600 to-fuchsia-600 px-6 py-3.5 font-semibold shadow-lg shadow-purple-950/60 transition hover:from-purple-500 hover:to-fuchsia-500">Get Started →</motion.button></Link><Link to="/jobs"><motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.98 }} className="rounded-xl border border-white/15 bg-white/5 px-6 py-3.5 font-semibold text-zinc-100 transition hover:border-purple-400/50 hover:bg-purple-400/10">Explore Jobs</motion.button></Link></div>
            <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-zinc-400">{["AI-assisted matching", "Candidate & recruiter tools", "One clear hiring workflow"].map((item) => <span key={item} className="flex items-center gap-2"><span className="text-emerald-400">●</span>{item}</span>)}</div>
          </motion.div>

          <motion.div initial={{ opacity: 0, scale: 0.96, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.1 }} className="relative mx-auto w-full max-w-xl">
            <div className="absolute inset-4 rounded-[2rem] bg-gradient-to-br from-purple-500/30 to-fuchsia-500/20 blur-2xl" />
            <div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[#13111e]/95 p-5 shadow-2xl shadow-black/50 sm:p-6">
              <div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-purple-500 to-fuchsia-600 text-sm font-bold">AI</div><div><p className="font-semibold">SmartHire Intelligence</p><p className="text-xs text-zinc-500">Live candidate-to-job matching</p></div></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1 text-xs font-medium text-emerald-300">Analysis ready</span></div>
              <div className="mt-5 grid gap-4 sm:grid-cols-[1fr_auto_1fr] sm:items-center">
                <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-purple-500/20 font-semibold text-purple-200">C</div><div><p className="text-sm font-semibold">Candidate profile</p><p className="text-xs text-zinc-500">Full-stack developer</p></div></div><div className="mt-4 flex flex-wrap gap-1.5">{["React", "Node", "MongoDB"].map((skill) => <span key={skill} className="rounded-md bg-purple-400/10 px-2 py-1 text-[10px] text-purple-200">{skill}</span>)}</div></div>
                <div className="relative mx-auto flex h-20 w-20 items-center justify-center rounded-full border-[6px] border-fuchsia-400/70 bg-fuchsia-400/10 text-center shadow-[0_0_36px_rgba(217,70,239,.25)]"><span className="text-lg font-bold">92%</span><span className="absolute -bottom-5 whitespace-nowrap text-[10px] uppercase tracking-wider text-fuchsia-200">match score</span></div>
                <div className="rounded-2xl border border-purple-400/25 bg-purple-500/10 p-4"><p className="text-xs text-purple-200">Recommended role</p><p className="mt-1 text-sm font-semibold">Frontend Developer</p><p className="mt-1 text-xs text-zinc-400">Open role · Bangalore</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-purple-400 to-fuchsia-400" /></div></div>
              </div>
              <div className="mt-8 grid grid-cols-3 gap-3">{[["Profile", "Complete"], ["Resume", "Analysed"], ["Hiring fit", "Strong"]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-1 text-xs font-semibold text-zinc-200">{value}</p></div>)}</div>
            </div>
            <motion.div animate={{ y: [0, -7, 0] }} transition={{ duration: 3.4, repeat: Infinity }} className="absolute -bottom-5 -left-3 rounded-xl border border-white/10 bg-[#1b1728] px-4 py-3 shadow-xl sm:-left-8"><p className="text-xs font-semibold">Resume insights updated</p><p className="mt-1 text-[11px] text-emerald-300">Skills detected successfully</p></motion.div>
          </motion.div>
        </section>

        <section className="mx-auto max-w-7xl px-6 py-10 md:px-10 lg:px-12"><div className="grid gap-6 rounded-3xl border border-purple-400/20 bg-gradient-to-br from-purple-950/50 via-[#171225] to-[#10101a] p-7 md:grid-cols-[1fr_.9fr] md:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-purple-300">Built for recruiters</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">Turn applications into confident hiring decisions.</h2><p className="mt-4 max-w-xl leading-7 text-zinc-400">Post roles, see every applicant, track application status, and find suitable candidates from one recruiter workspace.</p><Link to="/create-job" className="mt-6 inline-flex rounded-xl border border-purple-300/30 bg-purple-400/10 px-5 py-3 text-sm font-semibold text-purple-100 transition hover:bg-purple-400/20">Post a job →</Link></div><div className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="flex items-center justify-between"><p className="font-semibold">Hiring pipeline</p><span className="text-xs text-zinc-500">Recruiter view</span></div><div className="mt-6 space-y-4">{[["New applications", "12", "88%", "bg-purple-400"], ["Under review", "08", "62%", "bg-amber-400"], ["Shortlisted", "04", "36%", "bg-emerald-400"]].map(([label, count, width, color]) => <div key={label}><div className="flex justify-between text-sm"><span className="text-zinc-300">{label}</span><span className="font-semibold">{count}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className={"h-full rounded-full " + color} style={{ width }} /></div></div>)}</div></div></div></section>

        <section className="mx-auto max-w-7xl px-6 py-20 md:px-10 lg:px-12"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-purple-300">One platform, six tools</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">Everything your recruitment journey needs.</h2><p className="mt-4 text-zinc-400">Practical tools for candidates pursuing the right opportunity and recruiters building the right team.</p></div><div className="mt-11 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([icon, title, description], index) => <motion.div key={title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: index * 0.05 }} whileHover={{ y: -5 }} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 transition hover:border-purple-400/35 hover:bg-purple-400/[0.06]"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-purple-400/25 bg-purple-400/10 text-xs font-bold text-purple-200">{icon}</div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{description}</p></motion.div>)}</div></section>

        <section className="border-y border-white/10 bg-white/[0.025] py-20"><div className="mx-auto max-w-7xl px-6 md:px-10 lg:px-12"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-purple-300">How SmartHire-AI works</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">A clearer path for both sides of hiring.</h2></div><div className="mt-11 grid gap-6 lg:grid-cols-2">{workflows.map(([title, description, steps, gradient]) => <div key={title} className={"rounded-3xl border border-white/10 bg-gradient-to-br p-7 " + gradient}><p className="text-xl font-semibold">{title}</p><p className="mt-2 max-w-md text-sm leading-6 text-zinc-400">{description}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{steps.map((step, index) => <div key={step} className="rounded-xl border border-white/10 bg-black/20 p-4"><span className="text-xs font-bold text-purple-300">0{index + 1}</span><p className="mt-3 text-sm font-medium">{step}</p></div>)}</div></div>)}</div></div></section>

        <section className="mx-auto grid max-w-7xl gap-4 px-6 py-16 sm:grid-cols-3 md:px-10 lg:px-12">{[["AI-ready", "Skill-aware job recommendations"], ["Two-sided", "Purpose-built candidate and recruiter spaces"], ["One workflow", "Profiles, jobs, applications, and hiring tools"]].map(([value, label]) => <div key={value} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 text-center"><p className="text-2xl font-bold text-purple-200">{value}</p><p className="mt-2 text-sm text-zinc-400">{label}</p></div>)}</section>

        <section className="mx-auto max-w-7xl px-6 pb-24 pt-8 md:px-10 lg:px-12"><div className="relative overflow-hidden rounded-3xl border border-purple-400/25 bg-gradient-to-r from-purple-700/70 via-violet-700/55 to-fuchsia-700/60 px-7 py-14 text-center shadow-2xl shadow-purple-950/40 md:px-14"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full border border-white/15" /><div className="absolute -bottom-24 -left-16 h-56 w-56 rounded-full border border-white/15" /><div className="relative"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-purple-100">Your next move starts here</p><h2 className="mx-auto mt-4 max-w-3xl text-3xl font-bold md:text-5xl">Join SmartHire-AI and make hiring more intelligent.</h2><p className="mx-auto mt-5 max-w-2xl text-purple-100/80">Create your profile, discover relevant jobs, or start building your candidate pipeline today.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><Link to="/signup"><button className="rounded-xl bg-white px-6 py-3.5 font-semibold text-purple-800 transition hover:bg-purple-50">Create an account</button></Link><Link to="/jobs"><button className="rounded-xl border border-white/35 bg-white/10 px-6 py-3.5 font-semibold transition hover:bg-white/20">Explore opportunities</button></Link></div></div></div></section>
      </main>
    </div>
  );
}

export default Home;
